# Generated by Django 4.1.2 on 2022-10-24 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_lobby_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
